if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
source $HOME/.vim/vim-include-ordered/package.vim
source $HOME/.vim/vim-include-ordered/default-config.vim
source $HOME/.vim/vim-include-ordered/lsp-installer.lua
source $HOME/.vim/vim-include-ordered/lsp.lua

colorscheme one
set background=light
"colorscheme molokai

for include_file in uniq(sort(globpath(&rtp, 'vim-include/*.vim', 0, 1)))
    execute "source " . include_file
endfor

for include_file in uniq(sort(globpath(&rtp, 'vim-include/*.lua', 0, 1)))
    execute "luafile " . include_file
endfor
