
[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"

[language.javascript]
filetypes = ["javascript"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]

[language.html]
filetypes = ["html"]
roots = ["package.json"]
command = "html-languageserver"
args = ["--stdio"]

[language.typescript]
filetypes = ["typescript"]
roots = ["tsconfig.json"]
command = "typescript-language-server"
args = ["--stdio"]

[language.purescript]
filetypes = ["purescript"]
roots = ["package.json"]
command = "purescript-language-server"
args = ["--stdio"]
